### ISSUE TITLE
Crashes when searching for csgo

### ISSUE THREAD

**Issue by id535** [iisp33dii/si0n-Source#12]
If you open the cheat and then csgo, the program crashes

Can you fix please

**Comment by iisp33dii** [comment]
Working fine for me, did you forget to put the configs in the folder of the exe?

**Comment by id535** [comment]
I have the configs in the folder with the cheat but idk why it still crashes. But it doesn't matter so much because i can start csgo first and then the cheat and it works fine.

**Comment by id535** [comment]
But i have another issue now. After the new csgo update, i updated the offsets, but the aimbot only works with weapons that don't have skins. If you use a weapon with skins it just doesn't work...

**Comment by iisp33dii** [comment]
Ill update it within the next few days

**Comment by id535** [comment]
oh I figured it out. You now need to read the memory for item definition index as short not integer.

```
Public Function ID()
        Return mem.rdShort(ptr + m_iItemDefinitionIndex) 
    End Function
```
Instead of:
```
Public Function ID()
        Return mem.rdInt(ptr + m_iItemDefinitionIndex) 
    End Function

```

```
    Public Function rdInt(pOffset As Integer) As Integer
        Return BitConverter.ToInt32(rdMem(pOffset, 4), 0)
    End Function

    Public Function rdShort(pOffset As Integer) As Short
        Return BitConverter.ToInt16(rdMem(pOffset, 4), 0)
    End Function
```

**Comment by iisp33dii** [comment]
Aight, ill update it now
