### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iWonAMathsDebate** [iisp33dii/si0n-Source#4]
https://gyazo.com/78121b3890eb8d37bdcf1e9e69f6ea89

Get this when i open it, what am i doing wrong? xd

**Comment by iWonAMathsDebate** [comment]
the non-source version from oldschoolh... works just fine tho

**Comment by iisp33dii** [comment]
Localplayer offset was outdated, fixed it just now. try again

**Comment by iWonAMathsDebate** [comment]
Alright, i will, thanks for quick response btw!

**Comment by iWonAMathsDebate** [comment]
Yup, works! Have a great day <3
