### ISSUE TITLE
Update 19.01.17

### ISSUE THREAD

**Issue by iWonAMathsDebate** [iisp33dii/si0n-Source#5]
I don't want to be a nagging asshole, but the sig's are outdated. How can I find the signature/pattern to search for myself? o.O

**Comment by iWonAMathsDebate** [comment]
Lmao i just posted it seconds after your update xD. But still tho, how do you find them?

**Comment by iisp33dii** [comment]
1. Get new localplayer offset from UC or search it with CE idc.
2. Take new Offset - Outdated Offset, and change the offset in the sigscaning function to the outcome
4. ?
5. Profit

**Comment by iWonAMathsDebate** [comment]
Alright, thanks again ^^
