### ISSUE TITLE
Skinchanger

### ISSUE THREAD

**Issue by wiotq** [iisp33dii/si0n-Source#6]
Skinchanger isn't working, cant figure what's wrong.

**Comment by iisp33dii** [comment]
Just redownloaded the source, put the Offset and Config files into the folder started the cheat and 
--> skinchanger working fine

**Comment by wiotq** [comment]
Knfichanger works only :v

**Comment by iisp33dii** [comment]
You are doing something wrong then :| Do the skins of the weapons change?

**Comment by wiotq** [comment]
No, only knife's model change. I've downloaded the src compiled, put the config and offsets in same folder.

**Comment by iisp33dii** [comment]
Then try to debug it and find out why the skins are not set. You are updating the skins by pressing the skinchangerkey tho right?
