### ISSUE TITLE
Learning VB.Net and would like to code in CS:GO

### ISSUE THREAD

**Issue by eco999** [iisp33dii/si0n-Source#7]
Hi, I'm learning VB.Net for a College project and would really like to learn how to code a CS:GO cheat in the programming language. Do you have any tips on coding a cheat in VB.Net for CS:GO and where can I learn?

**Comment by iWonAMathsDebate** [comment]
Where you can learn?  - Right in front of your nose, maybe?
![image](https://cloud.githubusercontent.com/assets/22776360/22855941/6e2ca590-f088-11e6-9970-fe4dfa466624.png)

**Comment by iisp33dii** [comment]
To be honest there are so many resources on vb.net csgo cheats. And this repo is just one of them. I would suggets to trie and understand the code and then go and recreate it from the back of your mind.
