### ISSUE TITLE
Crash on debug

### ISSUE THREAD

**Issue by Jackiedk100** [iisp33dii/si0n-Source#8]
Hello,
Everytime I try to Start Debug the source it crashes.
https://hastebin.com/nebafuxiho.tex
This is the console on run.
Btw, if you can contact me private I will pay you for helping me too :)

**Comment by iisp33dii** [comment]
add me on steam /id/xs0
i just redownloaded it and it ran fine

**Comment by Jackiedk100** [comment]
You are added now

**Comment by Jackiedk100** [comment]
Tell me when you accept :D

**Comment by iisp33dii** [comment]
Problem fixed
